### ISSUE TITLE
Inst number

### ISSUE THREAD

**Issue by jose** [marcelosousa/progmerge#7]
Hi,

I've noticed there is mismatch between the `inst` number in the `log.txt` files that live in [here](https://github.com/marcelosousa/safemerge/tree/master/benchmarks/experiments/pldi/final) and the directory name.  For example,  the `benchmarks/experiments/pldi/final/kotlin/inst13/log.txt` file says `Inst: 184` but the directory is `inst13`.  Which one is correct?

--
Best,
Jose

**Comment by marcelosousa** [comment]
Hi @jose! You're right - let me look into this a bit more closely (it has been a while) to get you the right information.

**Comment by marcelosousa** [comment]
You should consider the directory name. The `log.txt` were generated using [git-merge-analyser](https://github.com/marcelosousa/safemerge/tree/master/tools/git-merge-analyser) and should be disregarded from the execution of `wiz`. I should have removed these files and provided more details on the results published at OOPSLA. This was a resubmission from PLDI and this is why they are still under PLDI. I'll try to clean this up and provide more details in the docs. If you have any other questions feel free to reach out.

**Comment by jose** [comment]
Ok, thanks.
